### ISSUE TITLE
Lock PC Command not working

### ISSUE THREAD

**Issue by bfish2** [LAB02-Research/HASS.Agent#104]
Lock PC command (as an entity) no longer works.  It previously did work as advertised at some point.  I'm not sure when it stopped working,

**Comment by LAB02-Admin** [comment]
Hey @bfish2,

Just tested and it's still working here, so not sure what's going on. Could you try removing the command, then click 'store and activate commands' (so it gets pushed to HA). Afterwards recreate it, using the same name, and again click 'store and activate commands'. 

Let me know if that helps, otherwise we'll keep debugging

**Comment by bfish2** [comment]
Thanks!  Just left this morning for vacation.  I'll do this when I get back
home on a week and update you then.  Happy 4th!

**Comment by bfish2** [comment]
Hello,

 

I did what you describe below, but no change.

 

Then, I deleted the existing entry and created a new entry using the name that HASS offered.  That now works as expected

 

So, I’m OK at present.

 

Thanks,

 

Brad

**Comment by LAB02-Admin** [comment]
Alright, glad it's working :)
