### ISSUE TITLE
Feature: minimize all windows

### ISSUE THREAD

**Issue by milandzuris** [LAB02-Research/HASS.Agent#109]
Hi i have question how to minimize all windows?

**Comment by LAB02-Admin** [comment]
Hey @milandzuris, you can create a Powershell command, and add this as the script:

```ps
(New-Object -ComObject Shell.Application).MinimizeAll()
```

But this is also a good idea for a new command, so I've created a ticket for it: [hassagent-121](https://lab02research.youtrack.cloud/issue/hassagent-121). For now you can use the script above.

I'm closing this GitHub ticket, not because I'm not doing it, but to keep everything centralised. I'll post back here when it's implemented :)

**Comment by milandzuris** [comment]
Hi thx for help, I made the script and it doesn't work.

![image](https://user-images.githubusercontent.com/42905545/177557010-9e0995bc-38a2-4e00-8c25-b15c14f81aeb.png)
![image](https://user-images.githubusercontent.com/42905545/177557077-df9d926b-daaa-4b4d-a993-28db7804f430.png)
![image](https://user-images.githubusercontent.com/42905545/177557116-71aa61a9-d370-4291-be7a-19afef68f781.png)

**Comment by milandzuris** [comment]
oooou sorry my bad thx for help
