### ISSUE TITLE
Bug: Microphone active sensor is always set to On

### ISSUE THREAD

**Issue by cazador481** [LAB02-Research/HASS.Agent#123]
The microphone active sensor is always set to on.

**To Reproduce**
Reboot computer
Open HASS agent
Open local sensors
See that microphone active last known state is ON

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 
![image](https://user-images.githubusercontent.com/119880/179545411-b03571b5-6278-4db6-aae2-d403c6ce1068.png)

 - Windows' UI language: 
 English
 - HASS.Agent version: 
![image](https://user-images.githubusercontent.com/119880/179545562-af85ed29-7f09-441f-a843-a99141545dbe.png)

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Additional context**

**Logs**
If possible, please provide the logs of HASS.Agent and - if applicable - the Satellite Service. You can find HASS.Agent's logs by going to the main window, then `Configuration` -> `Logging` -> `open logs folder`. The Satellite Service's logs are in the same window, but the `Satellite Service` tab -> `open service logs folder`. If you want, you can mail them to lab02research@outlook.com
[[2022-07-18] HASS.Agent_20220718.log](https://github.com/LAB02-Research/HASS.Agent/files/9133191/2022-07-18.HASS.Agent_20220718.log)
[2022-07-18_HASS.Agent.Satellite.Service_20220718.log](https://github.com/LAB02-Research/HASS.Agent/files/9133198/2022-07-18_HASS.Agent.Satellite.Service_20220718.log)

**Comment by ITensEI** [comment]
I've noticed this as well. Switching from HASS Workstation Service to this the Mic sensor always stays on.

**Comment by LAB02-Admin** [comment]
That's caused by an application using the microphone. Open regedit and go to this key:

`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\microphone`

Check all keys, and the 'NonPackaged' subkeys as well. If any application has a 0 for the `LastUsedTimeStop` value, it's using the microphone. Disable that application and check if the sensor changes.

If you find nothing, check this key as well:

`HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\microphone`

**Comment by cazador481** [comment]
I had 2 entries in the NonPackaged area, for programs that were not
running.  I deleted the keys, and now the microphone active is set to Off.
Thanks for the help
