### ISSUE TITLE
Feature: broadcast to all HASS.Agent clients in a /24 subnet

### ISSUE THREAD

**Issue by flossiesheep** [LAB02-Research/HASS.Agent#27]
Firstly, what a great little app, thankyou - this should be an integral part of Home Assistant...!

My wishlist would be a single command to "Notify all PC's", so don't have to manually repeat everything.
Ideally with a Broadcast sent to the /24 subnet, so then most users don't need to have fixed IP address and edit the configuration.

And then even better, enchanced with a "Notify Everything" command - PC's, iPhones, Android, Browser Mods, Remote Users, etc etc - all at one go! (I appreciate that is really a much-needed Core issue not yours...!)

**Comment by LAB02-Admin** [comment]
I'm closing most feature requests from github's issue list. They're not ignored, just moved to the [HASS.Agent Issue Tracker](https://lab02research.youtrack.cloud/) (you can find your link in a comment above). 

That tracker allows me to organise better through what's pending, being done, being released, etc. - instead of one long list, which is beginning to stress me out :p

I will however post a reply here when I've implemented your request!
