### ISSUE TITLE
Really high CPU usage

### ISSUE THREAD

**Issue by FiftyFour7250** [LAB02-Research/HASS.Agent#3]
Hi. I have i9-9900K. This is a powerful processor. And for some reason your app uses ~8.5% of it. Even a browser with almost a hundred open tabs uses less than 2%. For comparison, in Call of Duty Warzone used 25%. For what reason does your passive app, which is generally always minimized, use so much? Really much.
![image](https://user-images.githubusercontent.com/78786088/144295718-941903e3-415d-4796-8100-d9cc0ac802e7.png)

**Comment by LAB02-Admin** [comment]
I'm guessing it's because of a WMI sensor. What sensors did you add, and what are their refresh rates?

**Comment by FiftyFour7250** [comment]
Nothing. I use it only for notifications.
![image](https://user-images.githubusercontent.com/78786088/144305703-9f6838f7-fa65-4381-8108-d7ca47a09e16.png)

**Comment by LAB02-Admin** [comment]
Alright, I'll look into it and let you know

**Comment by LAB02-Admin** [comment]
Hi @FiftyFour7250, I just posted a new release that should address this issue. You can [download it here](https://github.com/LAB02-Research/HASS.Agent/releases/tag/v2021.12.2).

I had the same cpu issue on my machine, just didn't notice it, so I'm glad you did and thanks for posting the issue here :) 

Let me know if you find anything else, and I'll give you an heads-up when I've added the quickaction hotkeys.

**Comment by FiftyFour7250** [comment]
Yes, it's fixed. Thanks)
