### ISSUE TITLE
Feature: Quick Actions based on domain and get variables send from HA

### ISSUE THREAD

**Issue by Chreece** [LAB02-Research/HASS.Agent#40]
Hello Sam,

I hope you are doing well. Thank you very much for your time spending on this wonderful project.
Was wondering if is possible to have a dynamically change action menu in quick actions, based on the domain of the entity so to have any possible action taken (i.e. volume_up if media_player domain is choosed).

Also as I mentioned in https://github.com/LAB02-Research/HASS.Agent/issues/34#issuecomment-1068095433 this option would open a whole new world of possibilities for everyone.

Thank you again and enjoy your coffee :)

**Comment by LAB02-Admin** [comment]
Hey @Chreece,

You're welcome! I'm glad you like it :) 

Do you mean the 'action' dropdown menu when you create a new quickaction:

![image](https://user-images.githubusercontent.com/81011038/159155694-7eb0b3a2-070e-44be-8107-65be053f5171.png)

That it should only show the actions based on the domain you've selected? Or do you mean in the quickaction form itself?

I'm currently in the last phase of developing a satellite service ([#18]), so you can execute select commands and sensors without having to be logged in. This is taking way more time than I expected, because I want it done right and easy for everyone to use.

But when that's (finally) done, should be a week or two, I can get back to the other requests like [#34]. So I haven't forgotten!

Thank you for the coffee, really nice gesture to wake up with on this Sunday morning :)

**Comment by Chreece** [comment]
Yes exactly this dropdown menu I mean. 
My view on that is that it should give different options, based on the domain selected from the previous drop down menu. Now we are limited on the quick actions based on the options from this menu. 

Really nice to see how this useful application develops!
Keep up the good work Sam!

**Comment by LAB02-Admin** [comment]
Alright, will do!

**Comment by Chreece** [comment]
The variables are available and working like charm!
You are great!!!

**Comment by LAB02-Admin** [comment]
Thank you 😊

**Comment by LAB02-Admin** [comment]
By the way; there isn't an official way to get all the different states from HA, so I added them manually.

Let me know if there are states missing, and I'll add them
