### ISSUE TITLE
Feature: toggle to filter privacy-sensitive info from logs

### ISSUE THREAD

**Issue by VNRARA** [LAB02-Research/HASS.Agent#52]
Hey just a sidenote: 

2022-04-21 01:28:28.731 +02:00 [INF] [HASS_API] System connected with [domain]

The logs show external domains. Is it possible to hide that with a switch? 
People will most likely be posting lots of logs and this could be a security issue if forgotten to remove by the user.

**Comment by LAB02-Admin** [comment]
Very good point, will do, thanks!

[hassagent-48](https://lab02research.youtrack.cloud/issue/hassagent-48)

**Comment by LAB02-Admin** [comment]
I'm closing most feature requests from github's issue list. They're not ignored, just moved to the [HASS.Agent Issue Tracker](https://lab02research.youtrack.cloud/) (you can find your link in a comment above). 

That tracker allows me to organise better through what's pending, being done, being released, etc. - instead of one long list, which is beginning to stress me out :p

I will however post a reply here when I've implemented your request, and feel free to still post here when you have any questions/additions.
