### ISSUE TITLE
Feature: Ability to clear notifications

### ISSUE THREAD

**Issue by mdrichardson** [LAB02-Research/HASS.Agent#54]
Use case: I'd like to leave a persistent notification, but have it cleared as soon as a HA state changes.

I think there's a couple of ways this could be accomplished:

1. Similar to HA mobile notifications: notifications can have a `data.tag` attribute and then they get cleared if another notification is received with `message: 'clear_notification` and a `data.tag` that matches the one in the first notification, or
2. Add a `tag` to notifications and use a command to clear them (or maybe cleared by title, but tag might be better if titles are dynamic)

**Comment by LAB02-Admin** [comment]
Good idea :) I like the attribute to 'overwrite' previous notifications, that'd be useful for my usecases as well. I'll also add a 'clear all notifications' command.

I'll put it on the list

**Comment by LAB02-Admin** [comment]
I'm closing most feature requests from github's issue list. They're not ignored, just moved to the [HASS.Agent Issue Tracker](https://lab02research.youtrack.cloud/) (you can find your link in a comment above). 

That tracker allows me to organise better through what's pending, being done, being released, etc. - instead of one long list, which is beginning to stress me out :p

I will however post a reply here when I've implemented your request, and feel free to still post here when you have any questions/additions.
