### ISSUE TITLE
Bug: Port reservation failure copies bad command

### ISSUE THREAD

**Issue by mdrichardson** [LAB02-Research/HASS.Agent#55]
When setting up and port reservation fails, it mentions that a command is copied to the clipboard. The command that gets copied starts with `http add...` when it should start with `netsh http add...`

**Comment by LAB02-Admin** [comment]
Hey @mdrichardson,

Loving all the bug/feature reports, thanks for taking the time 😄 

This is actually a known bug, and it's fixed in the [latest beta](https://github.com/LAB02-Research/HASS.Agent/releases/download/b2022.11.2/HASS.Agent.Installer.exe) (or the new version I'm releasing this weekend). 

However, good catch (once again) that it doesn't copy the full command to the clipboard - I'll fix it

**Comment by mdrichardson** [comment]
No problem! Thanks for the great software!

**Comment by LAB02-Admin** [comment]
Fixed in [2022.11.3](https://github.com/LAB02-Research/HASS.Agent/releases/tag/v2022.11.3)
