### ISSUE TITLE
Feature: CPU temperature sensor

### ISSUE THREAD

**Issue by ikrowni** [LAB02-Research/HASS.Agent#57]
The availability of sensors in the project is great but I'm missing the CPU temp sensor. Anyway we could get this in the future?

**Comment by LAB02-Admin** [comment]
Hey @ikrowni,

Absolutely, they're on my shortlist. Those type of hardware sensors require elevated privileges, so they're only possible since the satellite service was introduced last month. 

I'll add them to the next release!

**Comment by ikrowni** [comment]
Awesome this has already allowed me to drop 3 add-ons with cpu temp I'll be able to drop the open hardware monitor component.

**Comment by LAB02-Admin** [comment]
I'm closing most feature requests from github's issue list. They're not ignored, just moved to the [HASS.Agent Issue Tracker](https://lab02research.youtrack.cloud/) (you can find your link in a comment above). 

That tracker allows me to organise better through what's pending, being done, being released, etc. - instead of one long list, which is beginning to stress me out :p

I will however post a reply here when I've implemented your request, and feel free to still post here when you have any questions/additions.
