### ISSUE TITLE
HASS.Agent Service queries homeassistant.local frequently.

### ISSUE THREAD

**Issue by jellewestenberger** [LAB02-Research/HASS.Agent#61]
Hello!

I noticed in the logs of my local dns server (AdGuard) that `homeassistant.local` gets queried about every 10s. This would only stop after I disabled the HASS.Agent service in Windows. 

I have configured HASS.Agent to use a custom https url to communicate with the HA API, which works without a problem, but for some reason `homeassistant.local` also gets queried.

Initially my dns server would return NXDOMAIN as it forwarded the query to a public dns server, but even after I configured it to point to my homeassistant host IP the queries still didn't stop. 
I don't know if reason for the frequent queries is that the DNS response is still invalid or that the response isn't cached, but as of now `homeassistant.local` accounts for about 25% of all queries that go through my dns server which messes up my statistics.

This isn't a breaking issue for me as HASS.Agent seems to function very well but I was wondering whether I can avoid these frequent queries? 

Any suggestions would be appreciated.

**Comment by LAB02-Admin** [comment]
Hi @jellewestenberger,

The service doesn't use the API, just MQTT. If you actually use the service, you can easily change this by entering a static IP here instead of the mDNS name:

![image](https://user-images.githubusercontent.com/81011038/166683639-07a9361d-ae3a-4577-a7b4-5c200ab44461.png)

If you don't use the satellite service, you can just set it to disabled:

![image](https://user-images.githubusercontent.com/81011038/166683753-963ea391-d6b9-4988-b25e-1a4a1831f8d7.png)

**Comment by jellewestenberger** [comment]
Hi @LAB02-Admin,

Thanks for your reply! 

In my configuration the MQTT broker's host had already been set to the correct static ip. So why is the satellite service still querying homeassistant.local? Is this a bug?

I would prefer to keep the service running so that I can still send hibernation or shutdown commands to my PC, even when the user is logged off.

**Comment by jellewestenberger** [comment]
Oh excuse me, I just noticed that there is a separate MQTT configuration tab inside the satellite service configuration window. There the host was indeed set to homeassistant.local. 

My bad!
