### ISSUE TITLE
Feature: separate MQTT topics for configuration and state reporting

### ISSUE THREAD

**Issue by ruifung** [LAB02-Research/HASS.Agent#63]
For example, my homeassistant instance has the discovery topic at homeassistant/discovery/#
But I would like hass.agent to have it's control topics at something like hassagent/#.

At present it stashes its state and control topics under homeassistant/discovery/#.

**Comment by LAB02-Admin** [comment]
Hi @ruifung,

Is `homeassistant/discovery/#` something you configured yourself? Because by default, hass.agent publishes to for instance `homeassistant/switch/{pc_name}/{switch_name}/config` and subsequently `homeassistant/switch/{pc_name}/{switch_name}/state`.

So as it is, everything's already categorized as entity type, device name and entity name.

I can see how moving the state topics to hass.agent's own root path would tidy things up a bit, but it would also take some work on my end to make that work. Are there any other reasons you'd like this?

**Comment by ruifung** [comment]
Yeah, it's something I configured myself on my installation. 
And yeah, it's mainly to tidy things up a bit, and for ACL reasons I suppose since I have rather fine grained ACL on my MQTT broker.

Since in my setup, almost all MQTT clients have limited access to only the topics they require.
 I.e. if they publish a HASS discovery entry, it's write-only to the discovery topics, and readwrite to their own topics.

**Comment by LAB02-Admin** [comment]
Sounds like you have an impressive configuration :) Very neat.

I'll see what I can do!

**Comment by LAB02-Admin** [comment]
I'm closing most feature requests from github's issue list. They're not ignored, just moved to the [HASS.Agent Issue Tracker](https://lab02research.youtrack.cloud/) (you can find your link in a comment above). 

That tracker allows me to organise better through what's pending, being done, being released, etc. - instead of one long list, which is beginning to stress me out :p

I will however post a reply here when I've implemented your request, and feel free to still post here when you have any questions/additions.
