### ISSUE TITLE
Feature: send additional identifiers in MQTT discovery payload

### ISSUE THREAD

**Issue by ruifung** [LAB02-Research/HASS.Agent#64]
It would be nice if MAC addresses / ip addresses /etc were sent in the discovery payload, if only so home assistant can correctly merge the resulting device with other entities from other integrations, i.e. unifi network.

**Comment by LAB02-Admin** [comment]
That's a great idea, thanks!

**Comment by LAB02-Admin** [comment]
I'm closing most feature requests from github's issue list. They're not ignored, just moved to the [HASS.Agent Issue Tracker](https://lab02research.youtrack.cloud/) (you can find your link in a comment above). 

That tracker allows me to organise better through what's pending, being done, being released, etc. - instead of one long list, which is beginning to stress me out :p

I will however post a reply here when I've implemented your request, and feel free to still post here when you have any questions/additions.
