### ISSUE TITLE
Feature: toggle display sleep mode

### ISSUE THREAD

**Issue by Jizzay1** [LAB02-Research/HASS.Agent#66]
Hi
Would love a command to turn the windows pc display off and on. Use case is a pc touchscreen that runs a Lovelace dashboard that I want to turn off in my kitchen when no motion and on when motion. Iot link has this and would allow me to transition over fully.

**Comment by LAB02-Admin** [comment]
Hi @Jizzay1,

That's actually on my todo list: [hassagent-11](https://lab02research.youtrack.cloud/issue/hassagent-11)

Won't be in the next version, but I'll try the one after that :)

**Comment by Jizzay1** [comment]
Thank you! In the meantime I figured out a custom command to turn off display using a powershell command, and turn on using a key press. No rush!

**Comment by LAB02-Admin** [comment]
Nice going! What PS command did you end up using?

**Comment by LAB02-Admin** [comment]
I'm closing most feature requests from github's issue list. They're not ignored, just moved to the [HASS.Agent Issue Tracker](https://lab02research.youtrack.cloud/) (you can find your link in a comment above). 

That tracker allows me to organise better through what's pending, being done, being released, etc. - instead of one long list, which is beginning to stress me out :p

I will however post a reply here when I've implemented your request, and feel free to still post here when you have any questions/additions.
