### ISSUE TITLE
Feature: Check if location disabled on laptop

### ISSUE THREAD

**Issue by JvdMaat** [LAB02-Research/HASS.Agent#69]
My work laptop has the location disabled via GPO:
![image](https://user-images.githubusercontent.com/90044149/170316456-9d254b39-03bd-4acf-980e-387069adeb14.png)

Which means the log just spams:
2022-05-25 09:09:53.946 -04:00 [FTL] [SENSOR] [i-jvandermaat_geolocation] Error publishing state: Access is denied. (0x80070005 (E_ACCESSDENIED))
(Literally every second)

Maybe build in a check to see if location is enabled on the OS and hide/gray out the Geolocation if unavailable.
On my end I'll just remove the sensor to stop the log spam.

**Comment by LAB02-Admin** [comment]
[[hassagent-88](https://lab02research.youtrack.cloud/issue/hassagent-88)]

**Comment by LAB02-Admin** [comment]
I'm closing most feature requests from github's issue list. They're not ignored, just moved to the [HASS.Agent Issue Tracker](https://lab02research.youtrack.cloud/) (you can find your link in a comment above). 

That tracker allows me to organise better through what's pending, being done, being released, etc. - instead of one long list, which is beginning to stress me out :p

I will however post a reply here when I've implemented your request, and feel free to still post here when you have any questions/additions.
