### ISSUE TITLE
Feature: Update GeoLocation to have Latitude and Longitude as attributes.

### ISSUE THREAD

**Issue by JvdMaat** [LAB02-Research/HASS.Agent#71]
Having them as Attributes instead of a string value would allow them to be used on a Map card.
(and potentially do geofencing with cell data enabled devices, or systems with broad enough WiFi range?)

**Comment by LAB02-Admin** [comment]
You're on fire :p

For this HASS.Agent needs to support attributes - it's on [the list](https://lab02research.youtrack.cloud/issue/hassagent-72). But yea afterwards the geolocation sensor can be upgraded - also [on the list](https://lab02research.youtrack.cloud/issue/hassagent-59) 😁

**Comment by JvdMaat** [comment]
I guess with that also comes... an Update sensor with appropriate attributes (for Windows Updates)? (Not sure if that would work in the HA framework, as the WU sensor does not work on either of my laptops, and I'm not sure if you can populate it with the correct data)
(And an update sensor for the HASS.Agent itself so we can alert on new agent updates centrally in HA. Especially useful if you monitor multiple systems that you do not regularly log in to)

**Comment by LAB02-Admin** [comment]
Yea the WindowsUpdates sensor is plannend to be upgraded when attributes are supported, because currently there's not enough space (255 chars max) to show the names of all pending updates - so it just shows a counter. But it probably won't support HA's own updating mechanism (not really an advantage to do so I think).

The HASS.Agent update sensor is nice, could even be accompanied by a UpdateAgent command so you can automatically update HASS.Agent remotely :)

[[hassagent-86](https://lab02research.youtrack.cloud/issue/hassagent-86)], [[hassagent-87](https://lab02research.youtrack.cloud/issue/hassagent-87)]

**Comment by LAB02-Admin** [comment]
I'm closing most feature requests from github's issue list. They're not ignored, just moved to the [HASS.Agent Issue Tracker](https://lab02research.youtrack.cloud/) (you can find your link in a comment above). 

That tracker allows me to organise better through what's pending, being done, being released, etc. - instead of one long list, which is beginning to stress me out :p

I will however post a reply here when I've implemented your request, and feel free to still post here when you have any questions/additions.
