### ISSUE TITLE
Sensor update interval not working

### ISSUE THREAD

**Issue by miit86** [LAB02-Research/HASS.Agent#8]
Hi,

sensor update interval is not working.
tried: 15 sec and 60 sec for volume.
GPU usage is by default at 300 sec.
but al sensors announce every second.

**Comment by LAB02-Admin** [comment]
Thanks, I'll look into it

**Comment by miit86** [comment]
Hi,

Noticed another thing: The application memory usage's keeps increasing with every sensor update.

**Comment by LAB02-Admin** [comment]
Thanks for the info @miit86, very helpful :) 

I'm going through the entire sensors code and adding new functionality (like 'multi-value sensors', for instance when you want to sent info of all drives, cpu cores, etc). That's why it's taking a bit longer (well that and the holidays). 

Should have a new version ready next week at the latest

**Comment by LAB02-Admin** [comment]
Hey @miit86,

The interval bug's fixed. I ran some extensive memory profiling & tracing on the latest version, with all sensors enabled, and couldn't find any leaks or significant increases. 

Could you please check to see if it's also fixed on your end? Otherwise please open a new ticket so we can figure it out.
