### ISSUE TITLE
Bug: installer crashes on launch

### ISSUE THREAD

**Issue by Kimosaj** [LAB02-Research/HASS.Agent#80]
Hi, I have an issue where the installer crashes every time I tried to open the "HASS.Agent.Installer.exe".
Than there is the window where I get asked if I want to agree to make changes to the system. I click on yes and a small window pops up fpr 1 second than another for maybe a half second and than its over nothing else and no program installed. My operation system is Windows 10 and I also have adminrights, so I dont think this is the issue. Any helping tips?

**Comment by LAB02-Admin** [comment]
Could you please run `winver.exe` and post a screenshot of its result? 

Then please start the installer and wait for it to crash again. Afterwards launch `eventvwr.exe`, then wait a bit while it loads all logs. When it's done, right click `Error` and click `View All Instances of This Event`. In the list that shows, please see if there are any relevant errors and post them here. 

![image](https://user-images.githubusercontent.com/81011038/173008384-5c3acf61-45ab-4ba8-a608-c0bf44460318.png)

**Comment by LAB02-Admin** [comment]
You're using a very old version of Windows 10, which hasn't been supported since 11th of May, 2021. Is there a reason you can't update? It might be a compatibility issue.

> Will a video, where you can see the crash, maybe help?

Depends, if you're seeing nothing but a quick flash or something, then not really :(

You could try installing manually: https://hassagent.readthedocs.io/en/latest/installation/#2-manual

**Comment by LAB02-Admin** [comment]
Closing this as W10 1809 isn't supported. Hopefully you can use the manual installation!

If there's anything else I can help with, let me know
