### ISSUE TITLE
Feature: Have webview remain open regardless of window focus

### ISSUE THREAD

**Issue by grastraa** [LAB02-Research/HASS.Agent#83]
Enjoying the new webview option recently introduced in a beta. 

It seems that the webview auto closes itself on loss of window focus. Without `keep loaded in the background` checked, it also forgets the set window location.

Could we have a setting to have webview remain open until we RMB the tray icon again? 
And ideally, remember the window location also?

**Comment by LAB02-Admin** [comment]
Sounds fair enough! I've created a feature request: [[hassagent-97](https://lab02research.youtrack.cloud/issue/hassagent-97)]

I'm closing this ticket, not because I'm not doing it, but to keep all issues centralised and the github list (relatively) clean. As soon as it's implemented, I'll reply here :) Thanks
