### ISSUE TITLE
Bug: Sensor timestamp doesn't match host time

### ISSUE THREAD

**Issue by Bodge-IT** [LAB02-Research/HASS.Agent#89]
Please make sure your bug isn't already listed on HASS.Agent's issue tracker:

https://lab02research.youtrack.cloud/

There's a list of open bugs & features on the right. On the left you can see what's being worked on, what's planned and what's ready for the next release.

If you're not sure, don't worry, just go ahead and we'll discuss :)

----

**Describe the bug**
Sensor timestamp is 1 hour behind PC time

**To Reproduce**
Windows 7 installed agent (2022.11.4) with one testing sensor active [sensor.lastactive]
PC timezone set to (UTC+00:00) Dublin, Edinburgh, Lisbon, London
Daylight saving on.

**Expected behavior**
Same time on sensor output as PC

![image](https://user-images.githubusercontent.com/1881642/174450473-bd29650f-d026-45c1-853a-7fc47bd3b8a1.png)

**Misc info (please complete the following information):**
![image](https://user-images.githubusercontent.com/1881642/174450518-3c01ef43-6e0a-4d7f-b02b-a1cecdf6dc6f.png)
United Kingdom language
 - HASS.Agent version: 2022.11.4

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Comment by LAB02-Admin** [comment]
Hi @Bodge-IT,

That's because the time is shown as an UTC value:

![image](https://user-images.githubusercontent.com/81011038/174979120-459481b1-e54a-4fbc-9ec1-f2dc763d622d.png)

The column is getting cut off for you though, you could manually widen it to show. The reason is that HA requires a certain timestamp format to make sure there are no conversion faults.

Just a fyi: Windows 7 isn't supported, and the new 2022.12.0 version won't work at all :(
