### ISSUE TITLE
Bug: HA floods 'Platform mqtt does not generate unique ID' notifications

### ISSUE THREAD

**Issue by jackyaz** [LAB02-Research/HASS.Agent#92]
My HA logs are being flooded with these messages from HASS Agent

Platform mqtt does not generate unique IDs. ID 0e0b0852-8b0b-437a-90da-064813858d6a already exists - ignoring sensor.jackyaz_hulk_memoryusage

Have I misconfigured something?

**Comment by LAB02-Admin** [comment]
Hi @jackyaz,

That could be because your sensors are published under another devicename that what they initially registered under. That can happen when your devicename changes, and the old one doesn't get properly cleaned.

You can use the `Home Assistant` part of the clean slate docs:

https://hassagent.readthedocs.io/en/latest/clean-slate/#home-assistant

The neatest way is to close HASS.Agent, just delete all instances of your HASS.Agent device in Home Assistant. Optionally restart HA to make sure the cache's clean as well, and then start HASS.Agent. It'll then reregister your device, commands and sensors (same name, so your automations etc keep working).

Hopefully that'll fix it for you, otherwise let me know :)

**Comment by jackyaz** [comment]
This worked, thanks!
