### ISSUE TITLE
Bug: WMI query not sent to MQTT

### ISSUE THREAD

**Issue by tunisiano187** [LAB02-Research/HASS.Agent#94]
**Describe the bug**
I'm using WMI query 
`SELECT * FROM Win32_PrintJob`
But since the last update, it take a very long time if i click the test button and results aren't sent to the mqtt broker.

**To Reproduce**
1. Create a local sensor for the query
2. Click on test

**Expected behavior**
Result quicker and sent to mqtt

**Screenshots**
![image](https://user-images.githubusercontent.com/6095739/175780035-5f1efa13-6720-4b3e-abc6-d666ffebccee.png)

**Misc info (please complete the following information):**
 - Windows build (ideally screenshot/info of `winver.exe` output): 
![image](https://user-images.githubusercontent.com/6095739/175780062-00debbb8-75cd-4805-b8b5-48e22bdcc73f.png)

 - Windows' UI language: French
 - HASS.Agent version:  
![image](https://user-images.githubusercontent.com/6095739/175780074-c621490d-bfdb-43da-ad38-a4eee9c5e565.png)

Please check what's applicable (multiple answers possible):

 - [x] Installed via installer
 - [ ] Installed manually
 - [x] Problem occurs in HASS.Agent
 - [ ] Problem occurs in Satellite Service

**Logs**
If possible, please provide the logs of HASS.Agent and - if applicable - the Satellite Service. You can find HASS.Agent's logs by going to the main window, then `Configuration` -> `Logging` -> `open logs folder`. The Satellite Service's logs are in the same window, but the `Satellite Service` tab -> `open service logs folder`. If you want, you can mail them to lab02research@outlook.com
[[2022-06-25] HASS.Agent_20220625.log](https://github.com/LAB02-Research/HASS.Agent/files/8985016/2022-06-25.HASS.Agent_20220625.log)

**Comment by LAB02-Admin** [comment]
Hi @tunisiano187,

When I enter `SELECT * FROM Win32_PrintJob` and hit `test wmi query`, I can an instant (empty) result. Can you please try rebooting and run the test again? Might be that your print spooler is bugged somehow.

About the result being sent, you've set the counter to 60 seconds, so it takes some time:

![image](https://user-images.githubusercontent.com/81011038/175806200-9cd46707-e444-45bd-8fb2-c5d4b4e2673e.png)

You can lower that value to have it pushed faster.

Sidenote: the sensor stays on 'unknown' when there's no printjob, since it just returns an empty value. So you should probably make a template sensor in Home Assisant to account for that.

I have a PrinterQueue sensor planned for next release: [[hassagent-13](https://lab02research.youtrack.cloud/issue/hassagent-13)].

**Comment by LAB02-Admin** [comment]
Closing this for now, if you need more help feel free to reopen!

**Comment by tunisiano187** [comment]
I've made many checks but still the same result...
Maybe this can help ?
![image](https://user-images.githubusercontent.com/6095739/179584488-72bd58ec-bdbc-42d0-bcb2-b7a6cdf1fbdf.png)
